### ISSUE TITLE
SoapySDRPlay doesn't report AGC support

### ISSUE THREAD

**Issue by xmikos** [pothosware/SoapySDRPlay2#13]
`SoapySDRUtil` reports `Supports AGC: NO` for SoapySDRPlay driver. Problem seems to be missing `hasGainMode` method in [Settings.cpp](https://github.com/pothosware/SoapySDRPlay/blob/master/Settings.cpp#L185) (`setGainMode` / `getGainMode` is not enough).

**Comment by cjcliffe** [comment]
Patched in now; thanks!
