### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by gedger** [pothosware/SoapySDRPlay2#18]
Any chance of creating a release 0.1  so I can add the driver to MacPorts?

Thanks

Richard

**Comment by guruofquality** [comment]
@cjcliffe This is basically your baby, how do you feel about a tag? Something like 0.1 would be fine or maybe a version that reflects the mirics api version? I'm happy to do it

**Comment by cjcliffe** [comment]
@guruofquality sure please do; I think SDRPlay team has a replacement in the works, but current source can be tagged as the first release.

**Comment by guruofquality** [comment]
Done: https://github.com/pothosware/SoapySDRPlay/tree/soapy-sdrplay-0.1.0

Throw something in the changelog if any fixes or major changes happen, thanks!
