### ISSUE TITLE
Problem in ReadPacket()

### ISSUE THREAD

**Issue by frspin** [pothosware/SoapySDRPlay2#19]
In CubicSDR and in gr-osmosdr I get some random holes in packet receiving, producing some seconds of silence in audio play.
Using gr-osmosdr with Gnuradio I get this message:
[CRITICAL] ds_mir_sdr_ReadPacket() error: 1

No problem using gr-osmosdr with device sdrplay directly, both with Gqrx and Gnuradio

SDRPlay API is 1.97
Soapy from github, self compiled
System is Ubuntu 16.04/64 bit up to date

This issue is sent also in SDRPlay Community forum

Regards
Franco Spinelli
IW2DHW

**Comment by SDRplay** [comment]
This method and API version isn't used any more so I suggest this is closed.

**Comment by vsonnier** [comment]
Thanks @SDRplay, closing this one up.
