### ISSUE TITLE
SoapySDRPlay CMake error on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by garytagg** [pothosware/SoapySDRPlay2#28]
Hello,
I am getting this CMake error when trying to build SoapySDRPlay

gary@gary-MSI-Wind-Ubuntu:~/SoapySDRPlay/build$ cmake ..
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "SoapySDR"
  (requested version 0.4.0) with any of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/gary/SoapySDRPlay/build/CMakeFiles/CMakeOutput.log".
===================
I believe I have followed the instructions listed in the SoapySDR Wiki to the letter.

The directory listing of SoapySDRPlay is:
gary@gary-MSI-Wind-Ubuntu:~/SoapySDRPlay$ ls
build          CMakeLists.txt        LICENSE.txt  Registation.cpp  SoapySDRPlay.hpp
Changelog.txt  FindLibSDRplay.cmake  README.md    Settings.cpp     Streaming.cpp

Any advice on how to proceed?

Thank you,
Gary

**Comment by guruofquality** [comment]
Primarily, that error means that the SoapySDRPlay cmake files cant find the cmake development files installed by SoapySDR. Can you share the output of make install for SoapySDR? Usually it will install files to: `/usr/local/share/cmake/SoapySDR/` by default

**Comment by guruofquality** [comment]
@garytagg This might be related to this issue: https://github.com/pothosware/pothos/issues/110 So my other suggestion is to move git cloned directories into a subdirectory (not home). It happens to confuse the build in this case. Sorry about that.

**Comment by garytagg** [comment]
Thank you for helping. I created a directory /home/gary/SDR and moved SoapySDRPlay under that.  I deleted the existing build directory but cmake still gives the same error, so I don't think this is related to #110.  There is no cmake directory in /usr/local/share.  I downloaded the prebuilt SoapySDR packages as described in this URL.  https://github.com/pothosware/pothos/wiki/Ubuntu.  The only packages not downloaded were the SDR Hardware packages as my hardware is SDRPlay. Do I need to uninstall the prebuilt packages and build SoapySDR manually?

**Comment by guruofquality** [comment]
>  I downloaded the prebuilt SoapySDR packages as described in this URL. https://github.com/pothosware/pothos/wiki/Ubuntu

In that case you just need the development files as well:
`sudo apt-get install libsoapysdr-dev`

**Comment by garytagg** [comment]
issue solved - thank you

**Comment by EEEEEEEEEEEEEEEEEEEIEEEEEEEEEEEEEEEEEE** [comment]
來吃酒

**Comment by technicalfiddles** [comment]
Edit - I somehow skipped initial installation of SoapySDR - https://github.com/pothosware/SoapySDR/wiki/BuildGuide. All working now.

The suggestion above to install the development files solved this same problem for me today. I was following the build instructions here: https://github.com/pothosware/SoapyRTLSDR/wiki
Installing on an RPI4 w Raspbian.
