### ISSUE TITLE
Device specific controls in GQRX

### ISSUE THREAD

**Issue by SDRplay** [pothosware/SoapySDRPlay2#37]
The device specific controls that are available via SoapySDRPlay do not seem to be accessible in GQRX. Is there any way for those controls to work?

Antenna switching is there for the RSP2, but things like BiasT or notch filters aren't.

**Comment by guruofquality** [comment]
At least with rtl and gr-osmosdr, one thing it does is throw the additional controls in with the device arguments so you can pass in misc key/value pairs to control things like the biasT.

It might be interesting to iterate through the args in the SoapySDRPlay constructor, and if any keys match the settings, call writeSetting with the key/value from the args. That way we can sneak it in :-)
