### ISSUE TITLE
Rewrite of the module with API v3.0 ?

### ISSUE THREAD

**Issue by vsonnier** [pothosware/SoapySDRPlay2#41]
Hello @SDRplay, are you planning to rewrite the SoapySDRPlay module with the API v3.0 to support 
double tuner access on RSPDuo ? 
For instance, allowing 2 CubicSDR instances in pseudo master / slave mode, running  a different tuner each ?

**Comment by SDRplay** [comment]
Yes it's on the list of things to do.

**Comment by vsonnier** [comment]
Thanks for the answer.
