### ISSUE TITLE
new tag?

### ISSUE THREAD

**Issue by ZeroChaos-** [pothosware/SoapySDRPlay2#45]
been a while, just a thought

**Comment by guruofquality** [comment]
My god, the poor changelog. @SDRplay no issues with me making a version tag for the current master branch of SoapySDRPlay?

**Comment by SDRplay** [comment]
None at all. In fact it would be good to version it now. The next version will most likely support the new API, so having a build that still supports the old API would be a good thing.

**Comment by guruofquality** [comment]
done

**Comment by ZeroChaos-** [comment]
thank you!
