### ISSUE TITLE
SoapySDRPlay::getHardwareInfo should return vendor ("SDRPlay") and model name too

### ISSUE THREAD

**Issue by jazzkutya** [pothosware/SoapySDRPlay2#52]
If you agree I will do it and make a pull request at some time.

**Comment by guruofquality** [comment]
Sounds like a good idea to me, actually getHardwareKey() should return the model too. And hardware info could use the serial number, and really anything else from the API that could be of use here. Much appreciated!

**Comment by guruofquality** [comment]
I did make sure the hardware key returns a string that represents the hardware: https://github.com/pothosware/SoapySDRPlay/commit/14ec39e4ff0dab7ae7fdf1afbbd2d28b49b0ffae Theres not a ton of extra info strings like there, so im not sure what else.
