### ISSUE TITLE
SDRPlay RSPDx hwVer == 4???

### ISSUE THREAD

**Issue by M0CRT** [pothosware/SoapySDRPlay2#66]
Hi

Just dropped the SDRPlay folks some questions regarding the enabling of the Bias T via Soapy on the RSPDx.  Whilst I can enable via Cubic (tested the voltage and 4.7v out).

If I attempt to do so via the Soapy string (utilising RTL_Airband), I don't get any voltage.  I wonder if this is to do with the lack of a hwVer 4 in the settings.ccp file and correctly enumerating the options and thus defaulting to an  V1 RSP?  Saying that, Cubic DOES enable this...so could it really be the API here?

My babble below.

If anyone could confirm what can be parsed via the string for the DX (and how to correctly enable the biasT...I would be much obliged).

Thanks

https://github.com/pothosware/SoapySDRPlay/blob/master/Settings.cpp

Breaks down the settings for Soapy specific for SDR Play devices.

Specific for the BiasT:
SoapySDR::ArgInfo BiasTArg;
BiasTArg.key = "biasT_ctrl";
BiasTArg.value = "true";
BiasTArg.name = "BiasT Enable";
BiasTArg.description = "BiasT Control";
BiasTArg.type = SoapySDR::ArgInfo::BOOL;
setArgs.push_back(BiasTArg);

and

else if (key == "biasT_ctrl")
{
if (biasTen == 0) return "false";
else return "true";

So may try using biasT_ctrl=1 rather than TRUE ( 0 and 1 are used as a boolean anyway and formatted True / False).

UPDATE.  Nope.

device_string = "driver=sdrplay,biasT_ctrl=1"

doesn't work either.  I note the SoapySDRPlay settings.ccp doesn't specifically address settings towards the DX

hwVer == 1 matches to RSP1????
hwVer == 2 matches to RSP2/RSP2Pro
hwVer == 3 matches to RSPduo
hwVer > 253 matches to RSP1A  

Don't see anything specific for the DX and that is hwVer 4 according to a probe of the device via SoapySDRUtil --probe.

I wonder if we need an update to SoapySDRplay as it will likely be falling back to the hwVer1 maybe?  Although the Antenna selection seem correct.

**Comment by SDRplay** [comment]
RSPdx requires the repository here: https://github.com/SDRplay/SoapySDRPlay

when it's proven and the API is out of beta, we can update the pothosware repository.
