### ISSUE TITLE
SoapySDRPlay not compiling with SDRplay_RSP_API-ARM64-3.07.1

### ISSUE THREAD

**Issue by ghost** [pothosware/SoapySDRPlay2#70]
The CMake process seems to fail with the latest development version of the binary driver.

> ubuntu@ubuntu:~/SoapySDRPlay/build$ cmake ..
> -- Build type not specified: defaulting to release.
> -- libsdrplay not found.
> CMake Error at CMakeLists.txt:16 (message):
> SDRPlay development files not found...
> 

Falling back to the legacy (SDRplay_RSP_API-ARM64-2.13.1) version fixes this issue.

**Comment by schnitzelbert** [comment]
Ok. Fix

**Comment by ghost** [comment]
Fixed by reading the manual. Will use https://github.com/SDRplay/SoapySDRPlay with v3 API.
